### PR TITLE
Review create custom player documentation

### PR DESCRIPTION
**Pull request by NPohl-MSFT**

### CODE REVIEW

**Comment by bethau** [comment]
> author: nopohl

This needs to be your github account name. So: NPohl-MSFT

---
Refers to: mixed-reality-docs/holographic-remoting-create-player.md:4 in eb9f6dd. [](commit_id = eb9f6dd5048f97e7dead1eb4788f48f093850710, deletion_comment = False)

**Comment by bethau** [comment]
> By creating a custom Holographic Remoting player app you can create an custom application capable of displaying [immersive views](app-views.md) from on a remote machine to your HoloLens 2 device. This article describes how this can be achieved. All code on this page and working projects can be found in the [Holographic Remoting samples github repository](https://github.com/microsoft/MixedReality-HolographicRemoting-Samples).

an custom application-> a custom application

---
Refers to: mixed-reality-docs/holographic-remoting-create-player.md:14 in eb9f6dd. [](commit_id = eb9f6dd5048f97e7dead1eb4788f48f093850710, deletion_comment = False)

**Comment by bethau** [comment]
> By creating a custom Holographic Remoting player app you can create an custom application capable of displaying [immersive views](app-views.md) from on a remote machine to your HoloLens 2 device. This article describes how this can be achieved. All code on this page and working projects can be found in the [Holographic Remoting samples github repository](https://github.com/microsoft/MixedReality-HolographicRemoting-Samples).

The first setence here doesn't make sense in the context of the player.

---
Refers to: mixed-reality-docs/holographic-remoting-create-player.md:14 in eb9f6dd. [](commit_id = eb9f6dd5048f97e7dead1eb4788f48f093850710, deletion_comment = False)

**Comment by bethau** [comment]
> >[!NOTE]

[!IMPORTANT] (same change has been made in create host docs)

---
Refers to: mixed-reality-docs/holographic-remoting-create-player.md:22 in eb9f6dd. [](commit_id = eb9f6dd5048f97e7dead1eb4788f48f093850710, deletion_comment = False)

**Comment by bethau** [comment]
> >Calling any Windows Mixed Reality related API before creating the player context can result in unexpected behavior as creating the player context will start redirecting the API calls. Ensure that the player context is created before interacting with any Mixed Reality related API. Never mix objects retrieved before the ```PlayerContext::Create()``` call with objects retrieved after the call.

This warning has been mostly rewritten in the host sample docs. Please adapt here as well.

---
Refers to: mixed-reality-docs/holographic-remoting-create-player.md:62 in eb9f6dd. [](commit_id = eb9f6dd5048f97e7dead1eb4788f48f093850710, deletion_comment = False)

**Comment by bethau** [comment]
> To connect from the player app to the host call the ```Connect``` method on the player context specifying the hostname and port. The default port is 8265.

Make the port number bold

---
Refers to: mixed-reality-docs/holographic-remoting-create-player.md:78 in eb9f6dd. [](commit_id = eb9f6dd5048f97e7dead1eb4788f48f093850710, deletion_comment = False)

**Comment by bethau** [comment]
> >[!NOTE]

[!IMPORTANT]

---
Refers to: mixed-reality-docs/holographic-remoting-create-player.md:91 in eb9f6dd. [](commit_id = eb9f6dd5048f97e7dead1eb4788f48f093850710, deletion_comment = False)

**Comment by bethau** [comment]
> Listening for incoming connections on the player app can be done by calling the ```Listen``` method. Both the handshake port and transport port can be specified during this call. The handshake port is used for the initial handshake. The data is then send over the transport port. By default port number 8265 and 8266 are used.

Make both port numbers bold.

---
Refers to: mixed-reality-docs/holographic-remoting-create-player.md:94 in eb9f6dd. [](commit_id = eb9f6dd5048f97e7dead1eb4788f48f093850710, deletion_comment = False)

**Comment by bethau** [comment]
> winrt::Microsoft::Holographic::AppRemoting::ConnectionState state = m_remoteContext.ConnectionState();

remote context? I don't think so ;-)

---
Refers to: mixed-reality-docs/holographic-remoting-create-player.md:144 in eb9f6dd. [](commit_id = eb9f6dd5048f97e7dead1eb4788f48f093850710, deletion_comment = False)

**Comment by bethau** [comment]
> On success, ```BlitRemoteFrame()``` returns ```BlitResult::Success_Color```. Otherwise it returns the failure reason. See the BlitResult enum documentation in the ```Microsoft.Holographic.AppRemoting.idl``` file for more details.

The BlitResult enum only has 3 values. We should explain it fully here instead of referencing the idl

---
Refers to: mixed-reality-docs/holographic-remoting-create-player.md:164 in eb9f6dd. [](commit_id = eb9f6dd5048f97e7dead1eb4788f48f093850710, deletion_comment = False)

**Comment by bethau** [comment]
> For more details, see the ```PlayerFrameStatistics``` documentation in the ```Microsoft.Holographic.AppRemoting.idl``` file.

where can I find the .idl file? Mention the NuGet package.

---
Refers to: mixed-reality-docs/holographic-remoting-create-player.md:175 in eb9f6dd. [](commit_id = eb9f6dd5048f97e7dead1eb4788f48f093850710, deletion_comment = False)

**Comment by FlorianBagarMicrosoft** [comment]
> By creating a custom Holographic Remoting player app you can create an custom application capable of displaying [immersive views](app-views.md) from on a remote machine to your HoloLens 2 device. This article describes how this can be achieved. All code on this page and working projects can be found in the [Holographic Remoting samples github repository](https://github.com/microsoft/MixedReality-HolographicRemoting-Samples).

remote machine to your HoloLens 2 device -> remote machine on your HoloLens 2.

---
In reply to: [516427927](https://github.com/FlorianBagarMicrosoft/mixed-reality/pull/4#issuecomment-516427927) [](ancestors = 516427927)

---
Refers to: mixed-reality-docs/holographic-remoting-create-player.md:14 in eb9f6dd. [](commit_id = eb9f6dd5048f97e7dead1eb4788f48f093850710, deletion_comment = False)

**Comment by FlorianBagarMicrosoft** [comment]
> Next the HolographicSpace can be created, by calling [HolographicSpace::CreateForCoreWindow(CoreWindow)](https://docs.microsoft.com/en-us/uwp/api/windows.graphics.holographic.holographicspace.createforcorewindow).

HolographicSpace::CreateForCoreWindow(CoreWindow) -> HolographicSpace.CreateForCoreWindow

---
Refers to: mixed-reality-docs/holographic-remoting-create-player.md:64 in 405be01. [](commit_id = 405be01b347ec5e1c6143a8db7cf40453862f83e, deletion_comment = False)

**Comment by FlorianBagarMicrosoft** [comment]
> m_playerContext = winrt::Microsoft::Holographic::AppRemoting::PlayerContext::Create();

This only works if you have the proper stuff in the appx manifest, right? If so we should make a note/important on that.

---
Refers to: mixed-reality-docs/holographic-remoting-create-player.md:57 in 405be01. [](commit_id = 405be01b347ec5e1c6143a8db7cf40453862f83e, deletion_comment = False)

**Comment by FlorianBagarMicrosoft** [comment]
> 2) OnDisconnected: Triggered if a established connection is terminated or a connection could not be established.

if a established ->  if an established

---
Refers to: mixed-reality-docs/holographic-remoting-create-player.md:120 in 405be01. [](commit_id = 405be01b347ec5e1c6143a8db7cf40453862f83e, deletion_comment = False)

**Comment by FlorianBagarMicrosoft** [comment]
> To display the the remotely rendered content, call ```PlayerContext::BlitRemoteFrame()``` while rendering a [HolographicFrame](https://docs.microsoft.com/en-us/uwp/api/windows.graphics.holographic.holographicframe). 

To display the the remotely -> To display the remotely

---
Refers to: mixed-reality-docs/holographic-remoting-create-player.md:149 in 405be01. [](commit_id = 405be01b347ec5e1c6143a8db7cf40453862f83e, deletion_comment = False)

**Pull request merged**
